### ISSUE TITLE
Consul domain name resolve problem in Azure

### ISSUE THREAD

**Issue by serxansherif** [hashicorp/learn-nomad-cluster-setup#22]
I deployed Nomad and Consul in Azure via Terraform. Cluster is running and I'm able to access Nomad and Consul web interface and run consul, nomad commads to check the clients and servers.

I deployed jobs to the Nomad cluster, but containers are not able to resolve consul domain names. 
Dig command output:
```
dig @127.0.0.1 -p 53 consul.service.frontend SRV

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 53 consul.service.frontend SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45724
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;consul.service.frontend.       IN      SRV

;; Query time: 2001 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Dec 13 07:53:17 UTC 2023
;; MSG SIZE  rcvd: 52
```
![image](https://github.com/hashicorp/learn-nomad-cluster-setup/assets/53265420/ca96767f-8cb3-468c-ae84-67f0aefdacdb)

could you help me to fix the issue pls?

**Comment by Ranjandas** [comment]
Hi @serxansherif,

The DNS name used in the query needs to be corrected. It should be `<service-name>.service.<consul>`. Could you let me know if you got this working?

I have a PR (https://github.com/hashicorp/learn-nomad-cluster-setup/pull/24) against this repository that would allow DNS resolution by default.

Feel free to try it out.

**Comment by serxansherif** [comment]
hi @Ranjandas 
thanks for your answer.
it started working after this PR.

Thanks again :)
