### ISSUE TITLE
where does the address "active.vault.service.consul" came from

### ISSUE THREAD

**Issue by migueldevmt** [hashicorp/learn-nomad-cluster-setup#6]
Im trying to configure a nomad cluster in a internal VPS, outside the three clouds services listed in this repo and i dont undestand where this domain of vault (active.vault.service.consul) came from; is this from SD of consul?

**Comment by momer** [comment]
Hey! Just browsing the repo and figured I'd answer your question (I'm not a maintainer/committer): that's a query which will be answered by [Consul DNS](https://developer.hashicorp.com/consul/docs/discovery/dns), which will return all of the nodes in the `active` state, under the `vault` service.

**Comment by migueldevmt** [comment]
aw ok, i gonna read more about, thank you for ur answer

**Comment by EugenKon** [comment]
@momer  Seems links are broken =(
